services:
  redis:
    image: redis:latest
    command: "redis-server --port ${REDIS_PORT}"
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - ${REDIS_DATA_PATH}:/data
    healthcheck:
      test: "redis-cli -p ${REDIS_PORT} ping"
      interval: 2s
      timeout: 20s
      retries: 10

  api:
    build: .
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      - REDIS_URL=redis://redis:${REDIS_PORT}
      - BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - APP_HOST=0.0.0.0
      - APP_PORT=${API_PORT}